config/routes.rb
Rails.application.routes.draw do
	get "/search", to: "articles#search"
	resources :articles do
		# get "/translate", to: "articles#translate"
		resources :article_answers
	end
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root to: "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :question, presence: true

	has_one :article_answer

	include PgSearch::Model

	before_save do
		self.question = Translator.instance.translate(self.question)
	end

	pg_search_scope(
		:search,
		against:{
			question: 'A',
			tag: 'B'
		},
		using: {
			tsearch: {
				tsvector_column: "tsv",
				dictionary: "english",
				highlight: {
					StartSel: '<b>',
					StopSel: '</b>',
					MaxWords: 123,
					MinWords: 456,
					ShortWord: 4,
					HighlightAll: true,
					MaxFragments: 3,
					FragmentDelimiter: '&hellip;'
				}
			}
		}
	)
end

app/models/article_answer.rb
class ArticleAnswer < ApplicationRecord
	validates :answer, presence: true

	belongs_to :article

	before_create do
		# perform machine translation
		self.translation = Translator.instance.translate(self.answer)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/article_answers_controller.rb
class ArticleAnswersController < ApplicationController
  before_action :set_article, only: [:new, :edit, :create, :update, :destroy]

  # GET /article_answers
  # GET /article_answers.json
  def index
    @article_answers = ArticleAnswer.all
  end

  # GET /article_answers/1
  # GET /article_answers/1.json
  def show
  end

  # GET /article_answers/new
  def new
    @article_answer = ArticleAnswer.new
  end

  # GET /article_answers/1/edit
	def edit
		# byebug
		@article_answer = @article.article_answer
  end

  # POST /article_answers
  # POST /article_answers.json
  def create
    @article_answer = @article.create_article_answer!(article_answer_params)
		respond_to do |format|
      if @article_answer.save
				# byebug
        format.html { redirect_to @article, notice: 'Article answer was successfully created.'}
        format.json { render :show, status: :created, location: @article }
      else
				byebug
        format.html { render :new }
        format.json { render json: @article_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /article_answers/1
  # PATCH/PUT /article_answers/1.json
	def update
		# byebug
		@article_answer = @article.article_answer
    respond_to do |format|
      if @article_answer.update(update_article_answer_params)
        format.html { redirect_to @article, notice: 'Article answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @article_answer }
      else
        format.html { render :edit }
        format.json { render json: @article_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /article_answers/1
  # DELETE /article_answers/1.json
	def destroy
		# byebug
    @article_answer = ArticleAnswer.find(delete_article_answer_params["id"])
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Article answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
		def set_article
			@article = Article.find(params[:article_id])
		end
		# def set_article_answer
    #   @article_answer = ArticleAnswer.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_answer_params
      # params.require(:article_answer).permit(:answer, :article_id, :id)
			params.require(:article_answer).permit(:answer)
		end

		def update_article_answer_params
			params.require(:article_answer).permit(:answer)
		end

		def delete_article_answer_params
			params.permit(:id)
		end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
		all_articles = Article.all
		@articles = ArticleDecorator.decorate_collection(all_articles)
  end

  # GET /articles/1
  # GET /articles/1.json
	def show
		@article = ArticleDecorator.find(params[:id])
		# byebug
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
	def edit
		@article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
	end

	def search
		search_params = params[:search]
		puts params
		r = Article.search(params[:q])
		@results = ArticleDecorator.decorate_collection(r)
		# byebug
		render "search_result"
	end

	# def translate
	# 	article_id = params[:article_id]
	# 	article = Article.find(article_id).decorate
	# 	article_answer_text = article.answer
	# 	translated_text = ::Translator.instance.translate(article_answer_text)
	# 	byebug
	# end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:question, :tag)
		end
end

app/views/article_answers/_form.html.erb
<%= simple_form_for @article_answer, url: article_article_answers_path, local: true do |f| %>
  <% if @article_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article_answer.errors.count, "error") %> prohibited this article_answer from being saved:</h2>

      <ul>
      <% @article_answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<%= f.input :answer, as: :text%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/article_answers/edit.html.erb
<h1>Editing Article Answer</h1>

<%= simple_form_for @article_answer, url: edit_article_article_answer_path(), local: true do |f| %>
  <% if @article_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article_answer.errors.count, "error") %> prohibited this article_answer from being saved:</h2>

      <ul>
      <% @article_answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<%= f.input :answer %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%# <%= link_to 'Show', @article_answer %>
<%# <%= link_to 'Back', article_answers_path %>

app/views/article_answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Article Answers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @article_answers.each do |article_answer| %>
      <tr>
        <td><%= link_to 'Show', article_answer %></td>
        <td><%= link_to 'Edit', edit_article_answer_path(article_answer) %></td>
        <td><%= link_to 'Destroy', article_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article Answer', new_article_answer_path %>

app/views/article_answers/new.html.erb
<h1>New Article Answer</h1>

<%= render 'form', article_answer: @article_answer %>

<%= link_to 'Back', article_article_answers_path %>

app/views/article_answers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_article_answer_path(@article_answer) %> |
<%= link_to 'Back', article_answers_path %>

app/views/articles/_form.html.erb
<%= simple_form_for @article, local: true do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<p><%= @article.question %></p>
	<%= f.input :question %>
	<%= f.input :tag %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_header.html.erb
<p id="notice"><%= notice %></p>

<h1> <%= link_to 'Knowledge Base', root_path %></h1>
<span class="d-inline">
<%= render 'search_form'%>
<%= link_to new_article_path do %>
	<%= icon('fas', 'plus-circle', class: 'strong') %>
<% end %>
</span>


<br/>

app/views/articles/_search_form.html.erb
<%= simple_form_for :search, url: search_path, method: "get", html: { class: 'form-inline' } do %>
	<%= text_field_tag(:q) %>
	<%= submit_tag("Search") %>
<%end%>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<main class="d-flex align-self-center justify-content-center">
	<div class="flex-column justify-content-center align-items-center">
		<%= render 'header' %>
	</div>
</main>

<br>

<% if @articles %>
<section class="d-flex flex-column">
	<% @articles.each do |article| %>
		<div class="d-flex flex-row shadow-lg p-3 mb-5 bg-white rounded">
				<span class="align-items-center">
					<%= link_to [article] do %>
						<p> <%= article.question  %> </p>
					<% end %>
					<p class="font-weight-bold"> #<%= article.tag %> </p>
					<p> <%= article.excerpt %>... </p>
				</span>
			<span >
				<%= link_to edit_article_path(article) do %>
					<%= icon('fas', 'edit')%>
				<% end %>

				<%= link_to [article], method: :delete, data: { confirm: 'Are you sure?' } do %>
					<%= icon('fas', 'trash')%>
				<% end %>
			</span>
		</div>
	<% end %>
</section>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/search_result.html.erb
<header class="col-lg-6 col-md-8 align-self-center">
<%= render 'header' %>
</header>

<% if @results %>
<% if @results.length == 0%>
<section class="d-flex flex-column">
	<div >
		<p class="font-weight-bold"> No results found! </p>
	</div>
</section>
<% else %>
<section class="d-flex flex-column">
	<% @results.each do |article| %>
		<div class="d-flex flex-row shadow-lg p-3 mb-5 bg-white rounded">
				<span class="align-items-center">
					<%= link_to [article] do %>
						<p> <%= article.question  %> </p>
					<% end %>
					<p class="font-weight-bold text-muted"> #<%= article.tag %> </p>
					<p> <%= article.excerpt %>... </p>
				</span>
			<span >
				<%= link_to edit_article_path(article) do %>
					<%= icon('fas', 'edit')%>
				<% end %>

				<%= link_to [article], method: :delete, data: { confirm: 'Are you sure?' } do %>
					<%= icon('fas', 'trash')%>
				<% end %>
			</span>
		</div>
	<% end %>
</section>
<% end %>
<% end %>

app/views/articles/show.html.erb
<h1> <%= link_to 'Knowledge Base', root_path %></h1>
<br />

<p id="notice"><%= notice %></p>
<h1> <%= @article.question %> </h1>

<div class="d-flex flex-row align-items-center">
<div class="align-self-center mx-2">
	<%= link_to "Edit question", edit_article_url(@article), class: "btn btn-secondary" %>
</div>
<% unless @article.has_answer? %>
<div class="align-self-center mx-2">
	<%= link_to "Add an answer", new_article_article_answer_url(@article.id), class: "btn btn-secondary" %>
</div>
<% end %>

<% if @article.has_answer? %>
<div class="align-self-end mx-2">
	<%= link_to edit_article_article_answer_url(@article.id), class: "btn btn-secondary" do %>
		<%= icon('fas', 'edit')%> Edit Answer
	<% end %>
</div>
<% end %>
</div>
<br />
<p> <%= @article.translation %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhraseChallengeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>